include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - prefer_final_locals
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures